//Inicio const
const favoritos1 = $("#descricao1")
const favoritos2 = $("#descricao2")
const favoritos3 = $("#descricao3")
const favoritos4 = $("#descricao4")
const favoritos5 = $("#descricao5")
const favoritos6 = $("#descricao6")
const favoritos7 = $("#descricao7")
const favoritos8 = $("#descricao8")
const favoritos9 = $("#descricao9")
const favoritos10 = $("#descricao10")

const descricaoFovorito1 = $("#descricaoFovorito1")
const descricaoFovorito2 = $("#descricaoFovorito2")
const descricaoFovorito3 = $("#descricaoFovorito3")
const descricaoFovorito4 = $("#descricaoFovorito4")
const descricaoFovorito5 = $("#descricaoFovorito5")
const descricaoFovorito6 = $("#descricaoFovorito6")
const descricaoFovorito7 = $("#descricaoFovorito7")
const descricaoFovorito8 = $("#descricaoFovorito8")
const descricaoFovorito9 = $("#descricaoFovorito9")
const descricaoFovorito10 = $("#descricaoFovorito10")
//Fim Const
//Inicio Script
favoritos1.on('click', function(){
    descricaoFovorito1.slideToggle(500)
    descricaoFovorito2.slideUp(1)
    descricaoFovorito3.slideUp(1)
    descricaoFovorito4.slideUp(1)
    descricaoFovorito5.slideUp(1)
    descricaoFovorito6.slideUp(1)
    descricaoFovorito7.slideUp(1)
    descricaoFovorito8.slideUp(1)
    descricaoFovorito9.slideUp(1)
    descricaoFovorito10.slideUp(1)
})
favoritos2.on('click', function(){
    descricaoFovorito2.slideToggle(500)
    descricaoFovorito1.slideUp(1)
    descricaoFovorito3.slideUp(1)
    descricaoFovorito4.slideUp(1)
    descricaoFovorito5.slideUp(1)
    descricaoFovorito6.slideUp(1)
    descricaoFovorito7.slideUp(1)
    descricaoFovorito8.slideUp(1)
    descricaoFovorito9.slideUp(1)
    descricaoFovorito10.slideUp(1)
})
favoritos3.on('click', function(){
    descricaoFovorito3.slideToggle(500)
    descricaoFovorito2.slideUp(1)
    descricaoFovorito1.slideUp(1)
    descricaoFovorito4.slideUp(1)
    descricaoFovorito5.slideUp(1)
    descricaoFovorito6.slideUp(1)
    descricaoFovorito7.slideUp(1)
    descricaoFovorito8.slideUp(1)
    descricaoFovorito9.slideUp(1)
    descricaoFovorito10.slideUp(1)
})
favoritos4.on('click', function(){
    descricaoFovorito4.slideToggle(500)
    descricaoFovorito2.slideUp(1)
    descricaoFovorito3.slideUp(1)
    descricaoFovorito1.slideUp(1)
    descricaoFovorito5.slideUp(1)
    descricaoFovorito6.slideUp(1)
    descricaoFovorito7.slideUp(1)
    descricaoFovorito8.slideUp(1)
    descricaoFovorito9.slideUp(1)
    descricaoFovorito10.slideUp(1)
})
favoritos5.on('click', function(){
    descricaoFovorito5.slideToggle(500)
    descricaoFovorito2.slideUp(1)
    descricaoFovorito3.slideUp(1)
    descricaoFovorito4.slideUp(1)
    descricaoFovorito1.slideUp(1)
    descricaoFovorito6.slideUp(1)
    descricaoFovorito7.slideUp(1)
    descricaoFovorito8.slideUp(1)
    descricaoFovorito9.slideUp(1)
    descricaoFovorito10.slideUp(1)
})
favoritos6.on('click', function(){
    descricaoFovorito6.slideToggle(500)
    descricaoFovorito2.slideUp(1)
    descricaoFovorito3.slideUp(1)
    descricaoFovorito4.slideUp(1)
    descricaoFovorito5.slideUp(1)
    descricaoFovorito1.slideUp(1)
    descricaoFovorito7.slideUp(1)
    descricaoFovorito8.slideUp(1)
    descricaoFovorito9.slideUp(1)
    descricaoFovorito10.slideUp(1)
})
favoritos7.on('click', function(){
    descricaoFovorito7.slideToggle(500)
    descricaoFovorito2.slideUp(1)
    descricaoFovorito3.slideUp(1)
    descricaoFovorito4.slideUp(1)
    descricaoFovorito5.slideUp(1)
    descricaoFovorito6.slideUp(1)
    descricaoFovorito1.slideUp(1)
    descricaoFovorito8.slideUp(1)
    descricaoFovorito9.slideUp(1)
    descricaoFovorito10.slideUp(1)
})
favoritos8.on('click', function(){
    descricaoFovorito8.slideToggle(500)
    descricaoFovorito2.slideUp(1)
    descricaoFovorito3.slideUp(1)
    descricaoFovorito4.slideUp(1)
    descricaoFovorito5.slideUp(1)
    descricaoFovorito6.slideUp(1)
    descricaoFovorito7.slideUp(1)
    descricaoFovorito1.slideUp(1)
    descricaoFovorito9.slideUp(1)
    descricaoFovorito10.slideUp(1)
})
favoritos9.on('click', function(){
    descricaoFovorito9.slideToggle(500)
    descricaoFovorito2.slideUp(1)
    descricaoFovorito3.slideUp(1)
    descricaoFovorito4.slideUp(1)
    descricaoFovorito5.slideUp(1)
    descricaoFovorito6.slideUp(1)
    descricaoFovorito7.slideUp(1)
    descricaoFovorito8.slideUp(1)
    descricaoFovorito1.slideUp(1)
    descricaoFovorito10.slideUp(1)
})
favoritos10.on('click', function(){
    descricaoFovorito10.slideToggle(500)
    descricaoFovorito2.slideUp(1)
    descricaoFovorito3.slideUp(1)
    descricaoFovorito4.slideUp(1)
    descricaoFovorito5.slideUp(1)
    descricaoFovorito6.slideUp(1)
    descricaoFovorito7.slideUp(1)
    descricaoFovorito8.slideUp(1)
    descricaoFovorito9.slideUp(1)
    descricaoFovorito1.slideUp(1)
})
//Fim sci